### PR TITLE
Truss element boundary conditions

### LINKED ISSUE #423: Fix replace! with different `BC` types in nodes, faces and elements boundary conditions
```julia
julia> typeof(boundary_conditions(s).node_bcs)
Dictionaries.Dictionary{FixedDof, Vector{Node{1, Float64}}}

julia> haskey(boundary_conditions(s).node_bcs, constant_gravity)
ERROR: MethodError: Cannot `convert` an object of type GlobalLoad to an object of type FixedDof

Closest candidates are:
  convert(::Type{T}, ::T) where T
   @ Base Base.jl:64

Stacktrace:
 [1] in(i::GlobalLoad, indices::Dictionaries.Indices{FixedDof})
   @ Dictionaries ~/.julia/packages/Dictionaries/7aBxp/src/AbstractIndices.jl:73
 [2] haskey(dict::Dictionaries.Dictionary{FixedDof, Vector{Node{1, Float64}}}, i::GlobalLoad)
   @ Dictionaries ~/.julia/packages/Dictionaries/7aBxp/src/AbstractDictionary.jl:37
 [3] top-level scope
   @ REPL[12]:1
   ```

### LINKED ISSUE #424: `GlobalLoad`  applied to `Truss` `Element`s

### PR DESCRIPTION
**Pull request by mvanzulli**
Closes #424 
Closes #423 
Preparation for #422

### CODE REVIEW

File: examples/clamped_truss/own_weight_clamped_truss.jl [hunk 1]
```diff
@@ -0,0 +1,117 @@
+# ---------------------------------
+# Own weight clamped truss example
```
Comment (mforets) [inline examples/clamped_truss/own_weight_clamped_truss.jl]:
```suggestion
# Clamped truss with self-weight
```
just noting that i think self-weight is the correct word

otherwise it sounds like it "owns" something, not that it is a property of the object.

File: examples/clamped_truss/own_weight_clamped_truss.jl [hunk 2]
```diff
@@ -0,0 +1,117 @@
...
+=#
+using ONSAS, Test
+using Dictionaries: dictionary
+
+"Return problem parameters"
+function parameters()
+    N = 10     # Number of elements.
+    E = 30e6    # Young's modulus.
+    ν = 0.3     # Poisson's ratio.
+    ρ = 750.0   # Density.
```
Comment (mforets) [inline examples/clamped_truss/own_weight_clamped_truss.jl]: just noting that in the future we can also plug in physical units via  https://github.com/PainterQubits/Unitful.jl/   
an advantage is that automatically checks for consistency of units in defining equations

File: examples/clamped_truss/own_weight_clamped_truss.jl [hunk 3]
```diff
@@ -0,0 +1,117 @@
...
+    # -------------------------------
+    material = SVK(; E, ν, ρ, label="material")
+    materials = StructuralMaterial(material => elements(mesh))
+    # -------------------------------
+    # Boundary conditions
+    # -------------------------------
+    fixed_bc = FixedDof(:u, [1], "fixed")
+    gravity_bc_ramp = GlobalLoad(:u, t -> t * [density(material) * g], "gravity")
+    node_bcs = dictionary([fixed_bc => [first(nodes(mesh))]])
+    element_bcs = dictionary([gravity_bc_ramp => elements(mesh)])
```
Comment (mforets) [inline examples/clamped_truss/own_weight_clamped_truss.jl]: did we not allow constructor without these dictionaries yet?

File: examples/clamped_truss/own_weight_clamped_truss.jl [hunk 4]
```diff
@@ -0,0 +1,117 @@
...
+    N = 10     # Number of elements.
+    E = 30e6    # Young's modulus.
+    ν = 0.3     # Poisson's ratio.
+    ρ = 750.0   # Density.
+    L = 200     # Element length.
+    A = 1       # Cross section area.
+    F = 10e6    # Force at the tip
+    g = 9.81    # Gravity
+    ϵ_model = RotatedEngineeringStrain
+    g, N, E, ν, ρ, L, A, F, ϵ_model
```
Comment (mforets) [inline examples/clamped_truss/own_weight_clamped_truss.jl]: in a case like this you may prefer to return a named tuple, so `(; g, N, ..)` then unpack it at the callsite in the same way `(; g, N, ...) = ...`. This prevents from potential bugs when reordering variables or removing / adding new ones.

File: examples/clamped_truss/own_weight_clamped_truss.jl [hunk 5]
```diff
@@ -0,0 +1,117 @@
...
+# Solution
+gravity_solution = solve!(gravity_analysis)
+# Tests
+# External force
+numerical_Fext = external_forces(last(states(gravity_solution)))
+analytical_Fext = [ρ * g * A * L / N for n in nodes(s)]
+analytical_Fext[1] = analytical_Fext[end] = ρ * g * A / 2 * L / N
+@test numerical_Fext ≈ analytical_Fext atol = 1e-6
+# Displacement
+numerical_u_last_node = last(displacements(gravity_solution, last(nodes(s)), 1))
```
Comment (mforets) [inline examples/clamped_truss/own_weight_clamped_truss.jl]: this is the kind of operation for which extending `displacements` with a new method that handles the time index too might be nice. cc @jorgepz

File: src/StructuralModel/StructuralBoundaryConditions.jl [hunk 6]
```diff
@@ -289,23 +289,26 @@ function Base.replace!(sb::StructuralBoundaryCondition,
 
     # node boundary conditions replacement
     node_boundary_conditions = node_bcs(sb)
-    if haskey(node_boundary_conditions, old_bc)
+    node_bc_type = eltype(keys(node_boundary_conditions))
+    if (old_bc isa node_bc_type) && haskey(node_boundary_conditions, old_bc)
```
Comment (mforets) [inline src/StructuralModel/StructuralBoundaryConditions.jl:293]: why is the new clause needed?

File: examples/clamped_truss/own_weight_clamped_truss.jl (hunk 2 above)
Comment (mvanzulli) [reply examples/clamped_truss/own_weight_clamped_truss.jl]: Nais, this checks every mathematical operation and the outcome units ? This may be expensive in computational terms ?

File: examples/clamped_truss/own_weight_clamped_truss.jl (hunk 3 above)
Comment (mvanzulli) [reply examples/clamped_truss/own_weight_clamped_truss.jl]: I think it should but didn't work, we can open an issue for this.

File: examples/clamped_truss/own_weight_clamped_truss.jl (hunk 5 above)
Comment (mvanzulli) [reply examples/clamped_truss/own_weight_clamped_truss.jl]: Ahhh okay, extend the `displacements` accessor by passing a `Vector{Int}`, this is related with #280  and #339

File: src/StructuralModel/StructuralBoundaryConditions.jl (hunk 6 above)
Comment (mvanzulli) [reply src/StructuralModel/StructuralBoundaryConditions.jl:293]: Ah okay, the thing here si that parametric type of the `BCtoEntitiy{BC,N} ` can be defined initially only with `FixedDof` boundary condition. Then the `haskey` method throws an error if the key that you are checking is a different type. This sth that u have to keep in mind if a BC replacement is done before defining the `StructuralBoundaryCondition` struct.

File: examples/clamped_truss/own_weight_clamped_truss.jl (hunk 4 above)
Comment (mvanzulli) [reply examples/clamped_truss/own_weight_clamped_truss.jl]: Done

File: examples/clamped_truss/own_weight_clamped_truss.jl (hunk 2 above)
Comment (mforets) [reply examples/clamped_truss/own_weight_clamped_truss.jl]: it has no runtime overhead actually > https://news.ycombinator.com/item?id=22151009

File: examples/clamped_truss/own_weight_clamped_truss.jl (hunk 3 above)
Comment (mforets) [reply examples/clamped_truss/own_weight_clamped_truss.jl]: indeed, we have this constructor https://github.com/ONSAS/ONSAS.jl/blob/main/src/StructuralModel/StructuralBoundaryConditions.jl#L46

Comment (mforets) [reply examples/clamped_truss/own_weight_clamped_truss.jl]: https://github.com/ONSAS/ONSAS.jl/issues/430

**Review by mforets — APPROVED** [review]
