### PR TITLE
minor changes in linear_extension

### LINKED ISSUE #343: unicode errors in linear extension
I get some unicode errors in Linux, that we checked with @mvanzulli that are related to the browsers and IDEs used.

image

and running the script:

```julia
julia> include("examples/linear_extension/linear_extension.jl")
ERROR: LoadError: UndefVarError: Lₖ not defined
Stacktrace:
 [1] macro expansion
   @ ~/work/onsas/ONSAS.jl_repo/examples/linear_extension/linear_extension.jl:65 [inlined]
 [2] macro expansion
   @ ~/.julia/packages/Suppressor/tQJeL/src/Suppressor.jl:127 [inlined]
 [3] run_linear_extension_example()
   @ Main ~/work/onsas/ONSAS.jl_repo/examples/linear_extension/linear_extension.jl:64
 [4] top-level scope
   @ ~/work/onsas/ONSAS.jl_repo/examples/linear_extension/linear_extension.jl:196
 [5] include(fname::String)
   @ Base.MainInclude ./client.jl:451
 [6] top-level scope
   @ REPL[3]:1
in expression starting at /home/jor/work/onsas/ONSAS.jl_repo/examples/linear_extension/linear_extension.jl:196
```

I propose slowly removing unicode characters at least from example scripts so that the code is easier to adopt for non unicode/julia users.

### PR DESCRIPTION
**Pull request by jorgepz**
closes #343

### CODE REVIEW

File: examples/linear_extension/linear_extension.jl [hunk 1]
```diff
@@ -14,31 +14,31 @@ function run_linear_extension_example()
     # -------------------------------
     ## scalar parameters
     E = 2.0             # Young modulus in Pa
-    ν = 0.4             # Poisson's ratio
+    nu = 0.4             # Poisson's ratio
```
Comment (mforets) [inline examples/linear_extension/linear_extension.jl:17]: `\nu` is probably fine here? or do you also experience issues with it?

File: examples/linear_extension/linear_extension.jl [hunk 2]
```diff
@@ -14,31 +14,31 @@ function run_linear_extension_example()
...
     # Boundary conditions
     # -------------------------------
     # Fixed dofs
     bc₁_label = "fixed-ux"
-    bc₁ = FixedDof(:u, [1], bc₁_label)
-    bc₂_label = "fixed-uj"
-    bc₂ = FixedDof(:u, [2], bc₂_label)
-    bc₃_label = "fixed-uk"
-    bc₃ = FixedDof(:u, [3], bc₃_label)
+    bc₁ = FixedDof([:u], [1], bc₁_label)
```
Comment (mforets) [inline examples/linear_extension/linear_extension.jl]: This needs to be a scalar, since handling vector inputs was removed in a recent PR.

File: examples/linear_extension/linear_extension.jl [hunk 3]
```diff
@@ -115,10 +114,10 @@ function run_linear_extension_example()
     # -------------------------------
     ## Displacements
     "Computes displacements numeric solution uᵢ, uⱼ and uₖ for analytic validation."
-    function u_ijk_analytic(λᵥ::Vector{<:Real}, x₀::Real, y₀::Real, z₀::Real, ν::Real=ν, E::Real=E)
-        𝐶(t) = tension(t) * (1 - ν - 2ν^2) / (1 - ν)
+    function u_ijk_analytic(λᵥ::Vector{<:Real}, x₀::Real, y₀::Real, z₀::Real, nu::Real=nu, E::Real=E)
+        C(t) = tension(t) * (1 - nu - 2nu^2) / (1 - nu)
```
Comment (mforets) [inline examples/linear_extension/linear_extension.jl]: Same comment; these should better use math notation imo.

File: examples/linear_extension/linear_extension.jl (hunk 1 above)
Comment (jorgepz) [reply examples/linear_extension/linear_extension.jl:17]: as discussed on friday. my proposal is to slowly remove Unicode from examples. particularly the introductory ones

File: examples/linear_extension/linear_extension.jl (hunk 3 above)
Comment (jorgepz) [reply examples/linear_extension/linear_extension.jl]: idem as the other conversation above

File: examples/linear_extension/linear_extension.jl (hunk 2 above)
Comment (jorgepz) [reply examples/linear_extension/linear_extension.jl]: done in [06d433a](https://github.com/ONSAS/ONSAS.jl/pull/344/commits/06d433a8d0a032a2c4867ed54d4817a927007e21) gracias!

File: examples/linear_extension/linear_extension.jl [hunk 4]
```diff
@@ -14,30 +14,30 @@ function run_linear_extension_example()
...
+    Lz = 1.0            # Dimension in z of the box in m
     RTOL = 1e-4         # Relative tolerance for tests
     NSTEPS = 9          # Number of steps for the test
     ms = 0.5            # Refinement factor
     # -------------------------------
     # Materials
     # -------------------------------
     mat_label = "mat"
-    mat = IsotropicLinearElastic(E, ν, mat_label)
+    mat = IsotropicLinearElastic(E, nu, mat_label)
```
Comment (mforets) [inline examples/linear_extension/linear_extension.jl:30]: The issue with `\nu` is that we're using this symbol in constructors, so when they are used as kwarg, the change wont apply -- would be better to fix this on the user end imho. 

I had a quick look and the reason the unicode is printed as boxes is due to missing fonts.

Comment (mforets) [reply examples/linear_extension/linear_extension.jl:30]: For example see constructors around https://github.com/ONSAS/ONSAS.jl/blob/main/src/Materials/SvkMaterial.jl#L49

Comment (jorgepz) [reply examples/linear_extension/linear_extension.jl:30]: this is not an issue in  `IsotropicLinearElastic` but indeed we have to discuss this for changes in other examples

**Review by mvanzulli — APPROVED** [review]

File: examples/linear_extension/linear_extension.jl [hunk 5]
```diff
@@ -127,19 +127,16 @@ function run_linear_extension_example()
...
     # point 2
     u_analytic_p₂ = u_ijk_analytic(load_factors(sa), p₂[1], p₂[2], p₂[3])
     uᵢ_analytic_p₂ = u_analytic_p₂[1]
-    uⱼ_analytic_p₂ = u_analytic_p₂[2]
-    uₖ_analytic_p₂ = u_analytic_p₂[3]
     ## Strains
     "Computes strains numeric solution ϵᵢ, ϵⱼ and ϵₖ for analytic validation."
-    function ϵ_ijk_analytic(λᵥ::Vector{<:Real}, x₀::Real, y₀::Real, z₀::Real, ν::Real=ν, E::Real=E)
-        𝐶(t) = tension(t) * (1 - ν - 2ν^2) / (1 - ν)
+    function ϵ_ijk_analytic(λᵥ::Vector{<:Real}, x₀::Real, y₀::Real, z₀::Real, nu::Real=nu,
```
Comment (mvanzulli) [inline examples/linear_extension/linear_extension.jl:135]: Do you want to keep \epsilon and \sigma and \lambda\_v? Maybe we can remove all the sub indexes and just keep simple greek letters. Imo every option is ok.

Comment (jorgepz) [reply examples/linear_extension/linear_extension.jl:135]: by now i think we can keep them since the main focus of this PR is to solve the visualization problems in the other unicode characters...
