### PR TITLE
Fix show method avoiding stats print 

### LINKED ISSUE #502: Fox `Base.show` method after using LinearSolve
Thanks to @tkrisnguyen we need to update the `Base.show` method for solutions.

### PR DESCRIPTION
**Pull request by mvanzulli**
Closes #502 

CC: @tkrisnguyen

### CODE REVIEW

File: src/StructuralSolvers/Solutions.jl [hunk 1]
```diff
@@ -55,7 +55,7 @@ solver(sol::AbstractSolution) = sol.solver
 Solution that stores all intermediate arrays during the analysis.
 """
 struct Solution{ST<:AbstractStaticState,A<:AbstractStructuralAnalysis,
-                SS<:Union{AbstractSolver,Nothing}} <: AbstractSolution
+                SS<:Union{AbstractSolver,SciMLBase.AbstractLinearAlgorithm}} <: AbstractSolution
```
Comment (mvanzulli) [inline src/StructuralSolvers/Solutions.jl:58]: This is removed for the case of `LinearStaticAnalysis` where only SciML linear algo is used. Instead of `Nothing` which is our internal representation for `Solver` we should point to the solver which is really used behind the scenes.

Comment (jorgepz) [reply src/StructuralSolvers/Solutions.jl:58]: ok

**Review by jorgepz — APPROVED** [review]
